resources:
  - url: http://127.0.0.1:5000/circle-sensor-card.js
    type: module
views:
  - cards:
      - type: custom:circle-sensor-card
        name: Circle Sensor Card v2 Development
        entity: sun.sun
        test_gui: true
